In [1]:
import pandas as pd
df = pd.read_csv('KQ.csv')
df

ID  AVG_score Fav_subject_1 Fav_subject_2 Fav_subject_3 Prize  \
0      1        8.5           Văn            Sử           Địa   Yes   
1      2        8.2          Sinh           Hoá          Toán   Yes   
2      3        7.8          Sinh           Địa           Hóa    No   
3      4        8.3           Anh           Văn            Sử   Yes   
4      5        8.2          Sinh           Hóa          Toán   Yes   
..   ...        ...           ...           ...           ...   ...   
595  596        6.7           Hóa          Sinh          Toán    No   
596  597        6.8          Toán           Anh            Lý   Yes   
597  598        6.9           Văn            Sử           Anh   Yes   
598  599        7.0          Toán           Hóa           Địa   Yes   
599  600        7.1          Sinh           Hóa           Văn   Yes   

        Hobby_1        Hobby_2       Hobby_3    Character     Career_trends_1  \
0     Viết lách       Chụp ảnh      Xem phim  Hướng ngoại            Sáng tạo   
1    Nghiên cứu      Viết lách   Tính nguyện    Hướng nội             Ổn định   
2      Làm vườn         Nấu ăn      Thủ công    Hướng nội  Cân bằng cuộc sống   
3    Nghiên cứu        Du lịch       Khảo cổ  Hướng ngoại               Tự do   
4    Nghiên cứu      Viết lách   Tình nguyện    Hướng nội             Ổn định   
..          ...            ...           ...          ...                 ...   
595  Nghiên cứu     Thí nghiệm      Đọc sách    Hướng nội             Trí tuệ   
596   Lập trình  Chơi thể thao  Chơi nhạc cụ    Hướng nội       Công nghệ cao   
597   Viết lách      Diễn kịch      Chụp ảnh  Hướng ngoại    Ảnh hưởng xã hội   
598   Lập trình       Làm vườn      Thủ công    Hướng nội       Công nghệ cao   
599  Nghiên cứu      Viết lách      Đọc sách    Hướng nội           Cống hiến   

      Career_trends_2 Career_trends_3                      Label  
0    Ảnh hưởng xã hội       Danh vọng               Truyền thông  
1               Tự do       Cống hiến                    Báo chí  
2           Cống hiến         Ổn định  Nông nghiệp công nghệ cao  
3           Cống hiến       Danh vọng                    Khảo cổ  
4               Tự do       Cống hiến                    Báo chí  
..                ...             ...                        ...  
595         Cống hiến         Ổn định         Công nghệ sinh học  
596           Trí tuệ       Lương cao          Phân tích dữ liệu  
597         Danh vọng           Tự do       Nghệ thuật biểu diễn  
598         Cống hiến        Khám phá           Kỹ thuật điện tử  
599           Ổn định         An toàn                   Dược học  

[600 rows x 14 columns]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import MultiLabelBinarizer

# ------------------------
# One Hot Encoding
# ------------------------
# Dùng sklearn OneHotEncoder

# Gom 3 cột Fav_subject thành một list
df["Fav_subjects"] = df[["Fav_subject_1", "Fav_subject_2", "Fav_subject_3"]].values.tolist()

# Multi-hot encoding
mlb = MultiLabelBinarizer()
fav_subject_encoded = pd.DataFrame(
    mlb.fit_transform(df["Fav_subjects"]),
    columns=mlb.classes_,
    index=df.index
)

df["Hobby"] = df[["Hobby_1", "Hobby_2", "Hobby_3"]].values.tolist()
mlb_hobby = MultiLabelBinarizer()
hobby_encoded = pd.DataFrame(
    mlb_hobby.fit_transform(df["Hobby"]),
    columns=mlb_hobby.classes_,
    index=df.index
)

df["Career_trends"] = df[["Career_trends_1", "Career_trends_2", "Career_trends_3"]].values.tolist()

mlb_career_trends= MultiLabelBinarizer()
career_trends_encoded = pd.DataFrame(
    mlb_career_trends.fit_transform(df["Career_trends"]),
    columns=mlb_career_trends.classes_,
    index=df.index
)

# Ghép vào dataframe gốc
df_encoded = pd.concat([df[["AVG_score", "Prize", "Character"]], fav_subject_encoded, hobby_encoded, career_trends_encoded], axis=1)

# ------------------------
# Label Encoding
# ------------------------
le_encoder = LabelEncoder()
df_encoded["Prize"] = le_encoder.fit_transform(df["Prize"])
df_encoded["Character"] = le_encoder.fit_transform(df["Character"])

print(df_encoded)


     AVG_score  Prize  Character  Anh  Hoá  Hóa  Lý  Sinh  Sử  Toán  ...  \
0          8.5      1          0    0    0    0   0     0   1     0  ...   
1          8.2      1          1    0    1    0   0     1   0     1  ...   
2          7.8      0          1    0    0    1   0     1   0     0  ...   
3          8.3      1          0    1    0    0   0     0   1     0  ...   
4          8.2      1          1    0    0    1   0     1   0     1  ...   
..         ...    ...        ...  ...  ...  ...  ..   ...  ..   ...  ...   
595        6.7      0          1    0    0    1   0     1   0     1  ...   
596        6.8      1          1    1    0    0   1     0   0     1  ...   
597        6.9      1          0    1    0    0   0     0   1     0  ...   
598        7.0      1          1    0    0    1   0     0   0     1  ...   
599        7.1      1          1    0    0    1   0     1   0     0  ...   

     Làm chủ  Lương cao  Phân tích dữ liệu  Quốc tế hóa  Sáng tạo  \
0          0      

In [3]:
X = df_encoded
y = le_encoder.fit_transform(df["Label"])
y

array([61,  0, 48, 22,  0,  7, 38,  0,  7, 28, 61, 48, 17, 12, 60,  8,  7,
        7, 12, 61, 48, 38, 17, 67, 10, 26,  8,  0, 65, 61, 49, 34, 12, 60,
        8, 67, 60, 26, 12, 61,  8, 67,  7, 49,  0, 17, 38, 10,  8, 12,  7,
       61, 37, 48, 34, 12, 26, 26, 12, 61,  8, 67,  7, 48,  0, 17, 38, 10,
        8, 12,  7, 61, 37, 49, 34, 12, 60,  8, 67, 17, 61,  7, 12, 61,  8,
       67, 65, 33,  1, 52, 19, 17, 33,  1, 52, 19, 65, 56, 53, 74, 64, 26,
       34, 63,  6, 58,  9, 18, 48, 38, 65, 70,  1, 17, 24, 69, 34, 17,  2,
       21, 52, 36, 25, 43, 71, 24, 33, 45,  3, 18,  6, 67, 14, 76, 17, 42,
       34, 33, 62, 74, 24, 15, 65, 67, 19, 13, 26, 48,  1, 17, 52, 70, 39,
       18, 23, 19,  9, 56, 33, 43, 17, 36, 23, 61, 70, 51, 26,  1, 20, 18,
       42, 19, 21, 63, 74, 65, 17, 33, 62, 52, 17, 36,  1, 50, 68,  9, 31,
       38, 45, 65, 42,  6,  7, 33, 51, 18, 74,  1, 50, 23, 56, 16,  7,  1,
       73, 41, 67,  7,  1, 73, 41, 16, 67, 29, 46, 40, 18,  1, 72, 30, 66,
       54,  7,  1, 75,  5

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# 4. Xử lý missing values: Nếu có missing values thì bạn có thể thay thế bằng median hoặc mode
# Ví dụ: Nếu có giá trị missing trong các cột số, ta thay thế bằng giá trị trung bình hoặc trung vị (median)
X = X.fillna(X.median())

# 5. Tách dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Khởi tạo mô hình Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# 7. Huấn luyện mô hình
model.fit(X_train, y_train)

# 8. Dự đoán với dữ liệu kiểm tra
y_pred = model.predict(X_test)

# 9. Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("📊 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n📈 Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.43333333333333335
📊 Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

📈 Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.29      0.33      0.31         6
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           6       0.43      0.50      0.46         6
           7       1.00      0.33      0.50         3
           8       0.50      0.50      0.50         2
           9       1.00      0.67      0.80         3
          10       1.00      1.00      1.00         1
          11       0.50      1.00      0.67         1
          12       0.50      0.50      0.50         2
          14       0.00      0.00      0.00         1
          17       0.57      0.57      0.57    

D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricW

In [5]:
for i, col in enumerate(X.columns, start=1):
    print(i, col)

1 AVG_score
2 Prize
3 Character
4 Anh
5 Hoá
6 Hóa
7 Lý
8 Sinh
9 Sử
10 Toán
11 Văn
12 Địa
13 Chơi cờ
14 Chơi game
15 Chơi nhạc cụ
16 Chơi thể thao
17 Chụp ảnh
18 Công nghệ
19 Diễn kịch
20 Du lịch
21 Khảo cổ
22 Làm vườn
23 Lập trình
24 Nghe nhạc
25 Nghiên cứu
26 Nấu ăn
27 Sáng tạo
28 Thí nghiệm
29 Thủ công
30 Tình nguyện
31 Tính nguyện
32 Viết blog
33 Viết lách
34 Xem phim
35 Đọc sách
36 An toàn
37 Cân bằng cuộc sống
38 Công nghệ cao
39 Cống hiến
40 Danh vọng
41 Khám phá
42 Làm chủ
43 Lương cao
44 Phân tích dữ liệu
45 Quốc tế hóa
46 Sáng tạo
47 Thăng tiến nhanh
48 Trí tuệ
49 Tự do
50 Ảnh hưởng xã hội
51 Ổn định


In [6]:
import pandas as pd

def raw_to_X_test(df_raw, X_columns):
    X_test = pd.DataFrame(0, index=df_raw.index, columns=X_columns)

    # Numeric
    if 'AVG_score' in X_columns:
        X_test['AVG_score'] = df_raw['AVG_score']

    # Prize
    if 'Prize_Yes' in X_columns:
        X_test['Prize_Yes'] = (df_raw['Prize'] == 'Yes').astype(int)

    # Character
    for idx, char in enumerate(df_raw['Character']):
        col_name = f'Character_{char}'
        if col_name in X_columns:
            X_test.loc[idx, col_name] = 1

    # Subjects (Fav_subject_1,2,3)
    for i in range(1, 4):
        if f'Fav_subject_{i}' in df_raw.columns:
            for idx, subj in enumerate(df_raw[f'Fav_subject_{i}']):
                col_name = subj
                if col_name in X_columns:
                    X_test.loc[idx, col_name] = 1

    # Hobbies (Hobby_1,2,3)
    for i in range(1, 4):
        if f'Hobby_{i}' in df_raw.columns:
            for idx, hobby in enumerate(df_raw[f'Hobby_{i}']):
                col_name = hobby
                if col_name in X_columns:
                    X_test.loc[idx, col_name] = 1

    # Career_trends (Career_trends_1,2,3)
    for i in range(1, 4):
        if f'Career_trends_{i}' in df_raw.columns:
            for idx, ct in enumerate(df_raw[f'Career_trends_{i}']):
                col_name = ct
                if col_name in X_columns:
                    X_test.loc[idx, col_name] = 1

    return X_test


In [7]:
import pandas as pd

data = {
    "AVG_score": [8.5],
    "Fav_subject_1": ["Toán"],
    "Fav_subject_2": ["Lý"],
    "Fav_subject_3": ["Hóa"],
    "Prize": ["Yes"],
    "Hobby_1": ["Nghiên cứu"],
    "Hobby_2": ["Xem phim"],
    "Hobby_3": ["Nghe nhạc"],
    "Character": ["Hướng nội"],
    "Career_trends_1": ["Lương cao"],
    "Career_trends_2": ["Khám phá"],
    "Career_trends_3": ["Thăng tiến nhanh"]
}

df_test_raw = pd.DataFrame(data)
df_test_raw

AVG_score Fav_subject_1 Fav_subject_2 Fav_subject_3 Prize     Hobby_1  \
0        8.5          Toán            Lý           Hóa   Yes  Nghiên cứu   

    Hobby_2    Hobby_3  Character Career_trends_1 Career_trends_2  \
0  Xem phim  Nghe nhạc  Hướng nội       Lương cao        Khám phá   

    Career_trends_3  
0  Thăng tiến nhanh

In [8]:
# df_test_raw là DataFrame dạng raw của bạn
X_test = raw_to_X_test(df_test_raw, X.columns)
# X_test
# # Bây giờ X_test có cùng cột với X.columns
y_pred = model.predict(X_test)


In [9]:
# Chuyển về nhãn gốc
y_pred_labels = le_encoder.inverse_transform(y_pred)

print(y_pred_labels)

['Kỹ sư phần mềm']


In [10]:
def predict_top5(model, label_encoder, X_test, top_n=5):
    # Xác suất dự đoán
    proba = model.predict_proba(X_test)  # shape: (n_samples, n_classes)
    
    # Nhãn model sử dụng
    classes = model.classes_  # numeric labels (encoded)
    
    # top 5 nhãn gốc
    top5_list = []

    # Nhãn predict() chính xác (top 1)
    y_pred_top1 = model.predict(X_test)  

    for i in range(X_test.shape[0]):
        # argsort xác suất giảm dần
        sorted_idx = np.argsort(-proba[i])
        top_indices = sorted_idx[:top_n]

        # đảm bảo top 1 = predict()
        top_indices = np.insert(top_indices, 0, np.where(classes == y_pred_top1[i])[0][0])
        top_indices = np.unique(top_indices)[:top_n]

        # Chuyển về nhãn gốc
        top_labels = label_encoder.inverse_transform(classes[top_indices])
        top5_list.append(top_labels)

    return pd.DataFrame(top5_list, columns=[f'Top{i+1}' for i in range(top_n)])


In [12]:
import numpy as np
# Dự đoán top 5
top5_df = predict_top5(model, le_encoder, X_test, top_n=5)

print(top5_df)

                  Top1                Top2            Top3               Top4  \
0  Công nghệ thông tin  Kinh doanh quốc tế  Kỹ sư phần mềm  Kỹ thuật phần mềm   

               Top5  
0  Trí tuệ nhân tạo  


In [13]:
import joblib

# giả sử model là RandomForestClassifier đã train
joblib.dump(model, "rf_model.pkl")

['rf_model.pkl']

In [15]:
import joblib

# Lưu cột
joblib.dump(list(X.columns), "model_columns.pkl")


['model_columns.pkl']

In [16]:
joblib.dump(le_encoder, "label_encoder.pkl")

['label_encoder.pkl']

In [14]:
# giả sử X là DataFrame train của bạn
X_test = raw_to_X_test(df_test_raw, X.columns)

print("Shape X_train:", X.shape)
print("Shape X_test:", X_test.shape)

# dự đoán
y_pred = model.predict(X_test)


Shape X_train: (600, 51)
Shape X_test: (1, 51)
